# name the compiler
CC = wcc386
WL = wlib
ASM = ml

!ifeq WATCOM9 yes
CFLAGS = /oeaxt /zp2 /4s /zq /s /DWATCOM9
!else
CFLAGS = /oeaxt /zp2 /5s /zq /s
!endif
LFLAGS = /c /q /b /n
#AFLAGS = /m2 /mx /z /p /q /t /jMASM51 /jQUIRKS
AFLAGS = /omf /Cx /Zm /c /W0 /Sa /DNoLanguage=SYSCALL /Djumps=;

OBJETS1  = P_SINTAB.obj P_ANIM.obj
OBJETS2  = P_OB_ISO.obj P_TRIGO.obj
OBJETS3  = P_FUNC.obj
OBJETS4  =

!ifeq WATCOM9 yes
LIB      = LB9_3D
!else
LIB      = LIB_3D
!endif

$(LIB).LIB: $(OBJETS1) $(OBJETS2) $(OBJETS3) $(OBJETS4)

	@echo $(OBJETS1) > clibmak.rsp
	@echo $(OBJETS2) >> clibmak.rsp
	@echo $(OBJETS3) >> clibmak.rsp
#	@echo $(OBJETS4) >> clibmak.rsp


	@$(WL) $(WLIBFLAGS) $(LIB) @clibmak.rsp
	@del clibmak.rsp
	@PRNTITRE G "$(LIB)"

.asm.obj:
	@PRNTITRE M "$*.ASM"
	@$(ASM) $(AFLAGS) $*.ASM

.c.obj:
	@PRNTITRE M "$*.C"
	@$(CC) $(WCFLAGS) $*
