# name the compiler
CC = wcc386
WL = wlib
ASM = ml

!ifeq WATCOM9 yes
CFLAGS   = /oaxet /s /zp2 /4s /zq /DWATCOM9
!else
CFLAGS   = /oaxet /s /zp2 /5s /zq /wx
!endif
LFLAGS = -b -n -c -q
#AFLAGS  = /m2 /mx /z /zi /t /jMASM51 /jQUIRKS
AFLAGS = /Cx /Zm /c /W0 /Sa /DNoLanguage=SYSCALL /Djumps=;


OBJETS1  = midi.obj ..\..\..\sdks\ail32\ail32.obj
OBJETS2  =
OBJETS3  =
OBJETS4  =

!ifeq WATCOM9 yes
LIB      = LB9_MIDI
!else
LIB      = LIB_MIDI
!endif

$(LIB).LIB: $(OBJETS1) $(OBJETS2) $(OBJETS3) $(OBJETS4)

	@echo $(OBJETS1) > clibmak.rsp

	@$(WL) $(LIBFLAGS) $(LIB) @clibmak.rsp
	@del clibmak.rsp
	@prntitre M "$(LIB) OK"

.asm.obj:
	@PRNTITRE M "$*.ASM"
	@$(ASM) $(AFLAGS) $*.ASM

.c.obj:
	@PRNTITRE M "$*.C"
	@$(CC) $(CFLAGS) $*
